### ISSUE TITLE
Create PV with all accessible memory in Block Device

### ISSUE THREAD

**Issue by HaykManukyanAvetiky** [openebs-archive/device-localpv#49]
this is more feature request rather than issue or bug.
When I am creating StatefullSet or other component and just specifying volumeClaimTemplate in order to automatically create bdc, pv and pvc openEbs  creates pvc -s with storage size specified in volumeClaimTemplate which leads to inefficient usage of bd.
# example
Lets say I have an 4 block devices in my cube cluster each 5G size.
When I create for example minio cluster with 4 nods with following volumeClaimTemplate 
``` 
volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: minio-openebs-local-device
```
it will create 4 pvc -s with 1Gi size, each connected with one bd and will 'lock' bd's so I will not be able to create other pv/pvc's.
This means I will use only 1Gi of my 5Gi drives.

So my request is the following.
as far as we can create only one pv/pvc on bd it will be more efficient to get all storage that we have. 
In my example even I requested 1Gi my volumes should be 5GI IN SIZE.
